# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            blacktop/volatility
            ghcr.io/${{ github.repository }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (v2)
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          context: ./2.6
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/volatility:2
            blacktop/volatility:2.6
            blacktop/volatility:2.6.1
            blacktop/volatility:latest
            ghcr.io/blacktop/volatility:2
            ghcr.io/blacktop/volatility:2.6
            ghcr.io/blacktop/volatility:2.6.1
            ghcr.io/blacktop/volatility:latest
          platforms: linux/amd64,linux/arm64            
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (plugins)
        id: docker_build_plugins
        uses: docker/build-push-action@v2
        with:
          context: ./plugins
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/volatility:plugins
            blacktop/volatility:2-plugins
            blacktop/volatility:2.6-plugins
            blacktop/volatility:2.6.1-plugins
            ghcr.io/blacktop/volatility:plugins
            ghcr.io/blacktop/volatility:2-plugins
            ghcr.io/blacktop/volatility:2.6-plugins
            ghcr.io/blacktop/volatility:2.6.1-plugins
          platforms: linux/amd64,linux/arm64            
          labels: ${{ steps.meta.outputs.labels }}
